[package]
name = "focaldesk-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2"
bitflags = "2"
smithay.workspace = true
nix = { version = "0.27", features = ["fs", "socket"] }
calloop = "0.12"
wayland-server = "0.31"
wayland-scanner = "0.31"
wayland-backend = "0.3"
wayland-protocols = { workspace = true, features = ["server", "staging"] }
serde = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zeroize.workspace = true
focaldesk-ui = { path = "../focaldesk-ui" }
focaldesk-ai = { path = "../focaldesk-ai" }
focaldesk-permissions = { path = "../focaldesk-permissions" }
focaldesk-flow = { path = "../focaldesk-flow" }
focaldesk-types = { path = "../focaldesk-types" }
focaldesk-logging = { path = "../focaldesk-logging" }
focaldesk-resources = { path = "../focaldesk-resources" }
focaldesk-cursor = { path = "../focaldesk-cursor" }
focaldesk-notifications = { path = "../focaldesk-notifications" }
focaldesk-settings-core = { path = "../focaldesk-settings-core" }
focaldesk-ipc = { path = "../focaldesk-ipc" }
focaldesk-themes = { path = "../focaldesk-themes" }
focaldesk-config = { path = "../focaldesk-config" }
focaldesk-sounds = { path = "../focaldesk-sounds" }
focaldesk-power = { path = "../focaldesk-power" }
focaldesk-audio = { path = "../focaldesk-audio" }
focaldesk-network = { path = "../focaldesk-network" }
focal-launch-shared = { path = "../focal-launch-shared" }
drm-ffi = { workspace = true }

serde_json = "1"
dirs = "6.0.0"
zbus = "3"
tokio = { version = "1", features = ["rt"] }
pipewire = "0.8"
egui = "0.31"
# Optional backend deps you control (examples)
winit = { version = "0.30", optional = true }
gl = "0.14.0"
fontdue = "0.9"
chrono.workspace = true
image.workspace = true
glow.workspace = true
libc = "0.2"
lcms2 = "6.1.1"
md5 = "0.7"
#winit



[features]
default = ["winit"]
winit = ["dep:winit"]
xwayland = ["smithay/xwayland"]
drm = []
