[package]
name = "flowos-compositor"
version = "0.1.0"
edition = "2021"

[dependencies]
smithay = { git = "https://github.com/Smithay/smithay", branch = "master", default-features = false, features = [
  "wayland_frontend",
  "desktop",
  "backend_winit",
  "renderer_gl",
  "winit"
] }
wayland-server = "0.31"
wayland-protocols.workspace = true
serde = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Optional backend deps you control (examples)
#winit = { version = "0.30", optional = true }
#winit

#[features]
#default = ["winit"]
#winit = ["dep:winit"]
#drm = []
