[workspace]
members = [

    # library crates
    "crates/focaldesk-types",
    "crates/focaldesk-engine",
    "crates/focaldesk-flow",
    "crates/focaldesk-ai",
    "crates/focaldesk-memory",
    "crates/focaldesk-ipc",
    "crates/focaldesk-settings-core",
    "crates/focaldesk-automation",
    "crates/focaldesk-ui",
    "crates/focaldesk-network",
    "crates/focaldesk-logging",
    "crates/focaldesk-voice",
    

    # apps
    "apps/focaldesk-cli",
    "apps/focaldesk-color-tag-test",
    "apps/focaldesk-wp-color-test",
    "apps/focaldesk-desktop",
    "apps/focaldesk-files",
    "apps/focaldesk-settings",

    # services
    "services/focaldesk-server", "crates/focaldesk-types", "crates/focaldesk-power", "crates/focaldesk-audio", "crates/focaldesk-bluetooth", "crates/focaldesk-notifications", "crates/focaldesk-resources", "crates/focaldesk-cursor", "crates/focaldesk-config", "crates/focaldesk-permissions", "apps/focaldesk-portal", "apps/focaldesk-settings", "crates/focaldesk-themes", "crates/focaldesk-sounds", "apps/focaldesk-ai-console", "crates/focal-launch-shared", "crates/focal-launchd", 
]
resolver = "2"

[workspace.dependencies]
smithay = { git = "https://github.com/Smithay/smithay", rev = "a394efa7058e987c89ffd90aa58b6ac13b2272a9", default-features = false, features = [
  "wayland_frontend",
  "desktop",
  "backend_winit",
  "backend_drm",
  "backend_gbm",
  "backend_libinput",
  "backend_udev",
  "backend_session_libseat",
  "renderer_gl",
  "use_system_lib",
  "xwayland"
] }
anyhow = "1"
nix = "0.27"
drm = "0.11"
drm-ffi = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
tracing-log = "0.2"
tracing-journald = "0.3"
wayland-protocols = "0.32.10"
serde = { version = "1.0", features = ["derive"] }
cosmic-text = "0.11"
swash = "0.1"
fontdb = "0.16"
usvg = "0.41"
resvg = "0.41"
tiny-skia = "0.11"
chrono = "0.4"
ab_glyph = "0.2"
image = "0.25"
glow = "0.16"
