[package]
name = "flowstate-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
flowstate-types = { path = "../flowstate-types" }
flowstate-themes = { path = "../flowstate-themes" }
flowstate-logging = { path = "../flowstate-logging" }
image = "0.25"
egui = "0.31"
egui_glow = "0.31"
glow.workspace = true

tiny-skia.workspace = true
cosmic-text.workspace = true
swash.workspace = true
fontdb.workspace = true
usvg.workspace = true
resvg.workspace = true
chrono.workspace = true
ab_glyph.workspace = true
anyhow.workspace = true
smithay = { workspace = true, features = ["renderer_gl"] }
