[package]
name = "flowstate-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2"
bitflags = "2"
smithay.workspace = true
nix = { version = "0.27", features = ["fs"] }
calloop = "0.12"
wayland-server = "0.31"
wayland-protocols.workspace = true
serde = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
flowstate-ui = { path = "../flowstate-ui" }
flowstate-flow = { path = "../flowstate-flow" }
flowstate-types = { path = "../flowstate-types" }
flowstate-logging = { path = "../flowstate-logging" }
flowstate-resources = { path = "../flowstate-resources" }
flowstate-cursor = { path = "../flowstate-cursor" }
flowstate-notifications = { path = "../flowstate-notifications" }
flowstate-settings-core = { path = "../flowstate-settings-core" }
flowstate-ipc = { path = "../flowstate-ipc" }
flowstate-themes = { path = "../flowstate-themes" }
flowstate-config = { path = "../flowstate-config" }
flowstate-sounds = { path = "../flowstate-sounds" }

serde_json = "1"
zbus = "3"
pipewire = "0.8"
egui = "0.31"
# Optional backend deps you control (examples)
winit = { version = "0.30", optional = true }
gl = "0.14.0"
fontdue = "0.9"
chrono.workspace = true
image.workspace = true
glow.workspace = true
#winit



[features]
default = ["winit"]
winit = ["dep:winit"]
xwayland = ["smithay/xwayland"]
drm = []
