pub mod client;
pub mod compositor;
pub mod data_device;
pub mod output;
pub mod portal_capture;
pub mod seat;
pub mod shm;
pub mod xdg_activation;
pub mod xdg_shell;
#[cfg(feature = "xwayland")]
pub mod xwayland;
