pub mod client;
pub mod clipboard_history;
pub mod color_management_protocol;
pub mod color_protocol;
pub mod compositor;
pub mod data_device;
pub mod dmabuf;
pub mod output;
pub mod pointer_constraints;
pub mod portal_capture;
pub mod seat;
pub mod shm;
pub mod trusted_shell;
pub mod xdg_activation;
pub mod xdg_shell;
#[cfg(feature = "xwayland")]
pub mod xwayland;
