pub mod app;
pub mod color;
pub mod consts;
pub mod desktop;
pub mod input;
pub mod layout;
pub mod linear_compositing;
pub mod lock;
pub mod output;
pub mod output_store;
pub mod render;
pub mod scene;
pub mod shell;
pub mod ui;
pub mod ui_state;
pub mod wallpaper;
pub mod wayland;
pub mod window_store;
pub mod workspace_store;
pub use focaldesk_ui::{chrome_layout, chrome_shaders};
pub mod backend_render;
pub mod focus;
pub mod fonts;
pub mod portal;
pub mod toplevel_interaction;
pub mod ui_builder;

// Re-export the “top-level” state types so `crate::core::X` works everywhere.
pub use app::App;
pub use output::OutputState;
pub use render::{FrameCtx, RenderState};
pub use scene::SceneState;
